swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/accounts:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Accounts API
      description: API for fetching a user Accounts Transactions
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: User Acounts Transactions retrieved successully
          schema:
            $ref: '#/definitions/UserAccountsResponse'
        '400':
          description: User unauthorize
        '500':
          description: Internal Server Error
  /user/accounts/{id}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: API to Get a user's Transactions by account Id
      description: Get transactions by user's account Id
      parameters:
        - in: path
          name: id
          type: integer
          required: true
      responses:
        '200':
          description: User Accounts retrieved successully
          schema:
              $ref: '#/definitions/Transactions'
        '400':
          description: User unauthorize
        '404':
          description: Transactions not founded
        '500':
          description: Internal Server Error
  /user/accounts/{id}/transactions/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: API to get user's single Transaction by Transaction Id
      description: Get Transaction by account Id and Transaction Id
      parameters:
        - in: path
          name: id
          type: integer
          required: true
        - in: path
          name: transactionId
          type: integer
          required: true
      responses:
        '200':
          description: User Accounts retrieved successully
          schema:
              $ref: '#/definitions/Transaction'
        '400':
          description: User unauthorize
        '404':
          description: Transaction not founded
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: API for updating a user Transaction
      description: Allows user to modify category and add notes in a transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: id
          type: integer
          required: true
        - in: path
          name: transactionId
          type: integer
          required: true
        - in: body
          name: body
          description: Update user Accounts Transactions attributes
          required: true
          schema:
            $ref: '#/definitions/UserTransaction'
      produces:
        - application/json
      responses:
        '200':
          description: User Accounts retrieved successully
          schema:
              $ref: '#/definitions/Transaction'
        '400':
          description: Invalid Fields
        '404':
          description: Transactions not founded
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  UserTransaction:
    type: object
    properties:
      transactionId:
        type: string
      category:
        type: string
      notes:
        type: string
  Transaction:
    type: object
    properties:
      transactionId:
        type: string
      transactionType:
        type: string
      description:
        type: string
      date:
        type: string
      category:
       type: string
      notes:
        type: string
      amount:
        type: integer
  Transactions:
    type: array
    items:
      $ref: '#/definitions/Transaction'
  UserAccountsResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
            type: object
            properties:
              accountType:
                type: string
              id:
                type: string
              userId:
                type: string
              balance: 
                type: number